### ISSUE TITLE
Update circe to 0.12.1

### ISSUE THREAD

**Issue by AlexBaitov** [scalapb-json/scalapb-circe#38]
https://github.com/circe/circe/releases/tag/v0.12.1

The problem of this update is that circe beginning from 0.12.0-M4 [droped](https://github.com/circe/circe/pull/1176) Scala 2.11 support. Or maybe it is a step forward.

**Comment by xuwei-k** [comment]
0.5.0 released
- https://github.com/scalapb-json/scalapb-circe/releases/tag/v0.5.0
- https://github.com/scalapb-json/scalapb-circe/pull/42
